version: "3"

services:
  db:
    container_name: store_manager_db
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - store_manager_net

networks:
  store_manager_net:
    driver: bridge